---
title: "Proyecto Final-Temperaturas"
author: "Luraghi-Rodriguez"
date: "June 18, 2018"
output: pdf_document
---



## INTRODUCCION

OBJETIVO:

Relaizar un análisis exploratorio de los datos utilizados para un proyecto cuyo objetivo general es la modelización y predicción de las temperaturas mínimas extremas en Uruguay, utilizando el enfoque
de la teoría de valores extremos.

La modelización de los eventos extremos climáticos resulta de particular interés en la actualidad, debido
al gran impacto que estos fenómenos producen tanto en la población como en los sectores productivos.
Estos últimos, que resultan especialmente sensibles a la variabilidad climática, adolecen en general de
un conocimiento confiable sobre la ocurrencia de sucesos extremos y les es imprescindible asignarles
ciertas probabilidades de ocurrencia. 

Uno de los objetivos específicos del proyecto sobre valores extremos consiste en comparar dos metodologías para la modelización, obteniendo predicciones de los niveles de retorno mediante el Método de Valores Extremos
por Bloques y el Método del Umbral. Además, se busca contrastar los resultados obtenidos mediante el
uso de los diversos paquetes del software estadístico R actualmente disponibles, por lo tanto realizaremos también la exploración de las bases de datos de valores extremos utilizadas para cada uno de los dos métodos mencionados.



## DATOS
La base de datos original está compuesta por registros diarios de temperaturas mínimas
de 26 estaciones meteorológicas de Uruguay para el período 2002-2014. Los datos están comprendidos
entre el 1o de enero de 2002 y el 31 de diciembre de 2014, lo cual implica un total de 4.526
observaciones por estación (118664 observaciones en total). 

La base incluye las siguientes variables:


* nroEstacion: Número de Estación
* lon: longitud en la cual se encuentra ubicada la Estación
* lat: Latitud en la cual se encuentra ubicada la Estación
* altitud: altura de la estación respecto al nivel del mar 
* anio: Año en el cual se registró la temperatura
* mes: Mes en el cual se registró la temperatura
* dia: Día en el cual se registró la temperatura
* tmin: valor en grados celsius de la temperatura mínima del día.
* modis1: Temperatura registrada por satélite
* modis2: Temperatura registrada por satélite 

Sin embargo para la realización del proyecto las variables a utilizar son: 
* número de estacion
* fecha: para tener un orden cronológico, creamos esta nueva variable a partir de las variables año, mes y día
* temperatura mínima registrada 
* coordenadas geograficas para un análisis espacial.
* departamento: asignada de acuerdo a la ubicación geográfica (latitud, longitud) de cada estación.




##ANALISIS EXPLORATORIO DE DATOS


Para la aplicación de métodos de teroría de extremos los datos no pueden ser estacionales ni dependientes(), por lo cual en primera instancia se corrobora con un gráfico de la serie.

hay estacionalidad? si

Hay outliers? Grafico de bxplot por trimestre (para meses de invierno)

Tabla de temperaturas mínimas por departamento: para ver si las mínimas se registraron en el mismo año y si hay una correlación de temperaturas y ubicación geografica( sur-centro-norte). Se agrega una variable mas

detallar que departamentos son parte de cada grupo.

hay correlacion entre las temperaturas mínimas y la altitud?


Plot de temperatura mínima registrada en cada año, (puede ser un plotly) coloreado por zona de estación. La idea es explorar si los mínimos siempre se dan en la misma zona o no. si hay una correlación.


Exploración espacial:

Se presentan dos mapas, uno en el cual se ubican las estaciones seleccionadas y otro que muestra las temperaturas mínimas por mes en cada departamento coloreado por las temperaturas.



##Metodologia: Métodos para elegir los datos con los cuales se aplicará la teoría de extremos

#Metodo del Umbral:


#Método de block máxima:





##Descripción de la aplicación shiny

A través de la aplicación Shiny, mostraremos el análisis exploratorio de los datos, aparecerán gráficos de la serie de temperaturas, pudiendo filtrar por numero de estación, y pudiendo ubicar geograficamente las mismas. Para todo el territorio uruguayo se podrá observar por mes las temperaturas mínimas registradas en cada departamento.









##Comentarios finales




## Referencias

-coles
-R
-librerias
